/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as LoginRouteImport } from './routes/login'
import { Route as TestsCreateRouteImport } from './routes/tests.create'
import { Route as TestsIdEditRouteImport } from './routes/tests.$id.edit'
import { Route as TestsIdPreviewRouteImport } from './routes/tests.$id.preview'
import { Route as TestsIdQuestionsRouteImport } from './routes/tests.$id.questions'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const TestsCreateRoute = TestsCreateRouteImport.update({
  id: '/tests/create',
  path: '/tests/create',
  getParentRoute: () => rootRouteImport,
} as any)
const TestsIdEditRoute = TestsIdEditRouteImport.update({
  id: '/tests/$id/edit',
  path: '/tests/$id/edit',
  getParentRoute: () => rootRouteImport,
} as any)
const TestsIdPreviewRoute = TestsIdPreviewRouteImport.update({
  id: '/tests/$id/preview',
  path: '/tests/$id/preview',
  getParentRoute: () => rootRouteImport,
} as any)
const TestsIdQuestionsRoute = TestsIdQuestionsRouteImport.update({
  id: '/tests/$id/questions',
  path: '/tests/$id/questions',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/login': typeof LoginRoute
  '/tests/create': typeof TestsCreateRoute
  '/tests/$id/edit': typeof TestsIdEditRoute
  '/tests/$id/preview': typeof TestsIdPreviewRoute
  '/tests/$id/questions': typeof TestsIdQuestionsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/login': typeof LoginRoute
  '/tests/create': typeof TestsCreateRoute
  '/tests/$id/edit': typeof TestsIdEditRoute
  '/tests/$id/preview': typeof TestsIdPreviewRoute
  '/tests/$id/questions': typeof TestsIdQuestionsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/login': typeof LoginRoute
  '/tests/create': typeof TestsCreateRoute
  '/tests/$id/edit': typeof TestsIdEditRoute
  '/tests/$id/preview': typeof TestsIdPreviewRoute
  '/tests/$id/questions': typeof TestsIdQuestionsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/login'
    | '/tests/create'
    | '/tests/$id/edit'
    | '/tests/$id/preview'
    | '/tests/$id/questions'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/dashboard'
    | '/login'
    | '/tests/create'
    | '/tests/$id/edit'
    | '/tests/$id/preview'
    | '/tests/$id/questions'
  id:
    | '__root__'
    | '/'
    | '/dashboard'
    | '/login'
    | '/tests/create'
    | '/tests/$id/edit'
    | '/tests/$id/preview'
    | '/tests/$id/questions'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DashboardRoute: typeof DashboardRoute
  LoginRoute: typeof LoginRoute
  TestsCreateRoute: typeof TestsCreateRoute
  TestsIdEditRoute: typeof TestsIdEditRoute
  TestsIdPreviewRoute: typeof TestsIdPreviewRoute
  TestsIdQuestionsRoute: typeof TestsIdQuestionsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tests/create': {
      id: '/tests/create'
      path: '/tests/create'
      fullPath: '/tests/create'
      preLoaderRoute: typeof TestsCreateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tests/$id/edit': {
      id: '/tests/$id/edit'
      path: '/tests/$id/edit'
      fullPath: '/tests/$id/edit'
      preLoaderRoute: typeof TestsIdEditRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tests/$id/preview': {
      id: '/tests/$id/preview'
      path: '/tests/$id/preview'
      fullPath: '/tests/$id/preview'
      preLoaderRoute: typeof TestsIdPreviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tests/$id/questions': {
      id: '/tests/$id/questions'
      path: '/tests/$id/questions'
      fullPath: '/tests/$id/questions'
      preLoaderRoute: typeof TestsIdQuestionsRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashboardRoute: DashboardRoute,
  LoginRoute: LoginRoute,
  TestsCreateRoute: TestsCreateRoute,
  TestsIdEditRoute: TestsIdEditRoute,
  TestsIdPreviewRoute: TestsIdPreviewRoute,
  TestsIdQuestionsRoute: TestsIdQuestionsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
